### ISSUE TITLE
Donation Total Calculations...

### ISSUE THREAD

**Issue by BBHLF** [scottag99/myhomelibrary#97] opened 2017-04-25 22:43 UTC
Summer '17 Blackshear Elementary campaign - campaign detail page - sort by donation total largest to smallest.  The six largest donations show $180 each.  Is that accurate?  Might it be six donations of $30 each? Is this calculation inflating the donation total/donations made on the Organization Detail and admin dashboard.   

http://www.myhomelibraryhouston.org/admin/organizations/4/campaigns/7

Teacher
K Phillips - $180
T Monroe - $180
R Glasscock - $180
C White - $180
T Bill - $180
A Landry - $180

**Comment by scottag99** [comment] 2017-04-26 22:11
This is related to issue #95 where the donation amount is not getting split across the multiple selected wish lists. This is skewing the calculations. I'm closing this issue since it is a duplicate of the other and correcting #95 will resolve this issue.

**Closed by scottag99** 2017-04-26 22:11 UTC
